name: 📝 Help request
description: "Ask a question."
labels:
 - "Help"
body:
 - type: markdown
   attributes:
    value: |-
     Please make sure you are using a recent version of the plugin.

 - type: checkboxes
   attributes:
    label: "Confirmation"
    description: "Please confirm to have done the following checks before opening a new issue."
    options:
     - label: "I have read the [documentation](https://filoghost.me/docs/chest-commands)."
       required: true
     - label: "I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq)."
       required: true

 - type: textarea
   attributes:
    label: "Description"
    description: "Describe your goal and what you have tried so far."
    placeholder: "What are you trying to achieve? What have you tried so far?"
   validations:
    required: true

 - type: input
   attributes:
    label: "Chest Commands version"
    description: "Output of the command `/version ChestCommands`."
    placeholder: "ChestCommands version 4.0.4-SNAPSHOT-b75"
   validations:
    required: true

 - type: textarea
   attributes:
    label: Additional information
    description: |-
     Relevant attachments such as **screenshots**, **server logs**, **configurations files** or any other additional information that might be useful.
     Text files can also be uploaded to [Pastebin](https://pastebin.com) and shared through the generated link.
